### ISSUE TITLE
Some details about implements

### ISSUE THREAD

**Issue by CloudFlyCN** [tensorflow/privacy#39]
1. I have known the reason about why you add noise after accumulating all gradients in one batch, but I wonder why you use` 'Query' ` which sounds like an operation in database to accumulate gradients?
2. In `GaussianSumQuery` class, there is variable called `'global_state'`, but during debug stage, it is always None?
Thanks

**Comment by npapernot** [comment]
1. The terminology is in common with other frameworks that rely on the dp average query object like federated learning. That's why it uses the term "query".

2. The global state is updated by the dp average query object each time a noisy gradient is returned by the dp average query object. You can see that in the implementation of the DP optimizer. 

Maybe @galenmandrew can comment more if needed. Also feel free to reopen if this does not answer your  questions

**Comment by galenmandrew** [comment]
The DPQuery interface includes a global_state that can maintain any state that changes across samples. However GaussianSumQuery does not have any such state so the global_state is None.

**Comment by CloudFlyCN** [comment]
Thanks a lot for all of you!
